### PR TITLE
USBMap installation

### PR DESCRIPTION
**Pull request by Kinetik**
USBMap is how real macs identify their ports. USBInjectall is meant to be a solution with a large spectrum, so that "it works" is some way. But if not correctly mapped, this can have severe influence on power management everywhere.

### CODE REVIEW

**Comment by Xtendera** [comment]
Hey @Kinetik, maybe you should move the second commit to a different branch as it is not part of this issue/pull request.

**Comment by varszegimarcell** [comment]
Hey! 

Thank you for making the USB maps! I know USBInjectAll is the lazy way, but it worked OK for me at least.

I want to ask that this map would work universally with the M/SFF/MT models, or is it for one specific machine?

**Comment by Xtendera** [comment]
I believe (and correct me if I am wrong) they are universal between the models.

**Comment by Kinetik** [comment]
I could not say really. Maybe, maybe not! I would need a export of IORegistryExplorer.app from each type of machine running with USBInjectall.

**Comment by jayphizzle** [comment]
Hi! I updated to the latest version. But with this my BCM94360NG will not be fully recognized.
WLAN is working but Bluetooth does not show up.

Any Idea how to fix this? I should work out of the box.

**Comment by Xtendera** [comment]
I am not an expert in USB Mapping (I have never done it before), so you will have to wait until Kinetik answers your question. Also, can you please tell me your Optiplex 3020 type (SSF, MT, etc.)?

**Comment by Kinetik** [comment]
Hi. Are they both on PCIe or plugged into UBS's?

**Comment by Kinetik** [comment]
Unfortunatelly, i do not have this hardware (yet, planning on buying). We can only support standard hardware for this unit. This is mostly because there are too many such cards that can fit and we cannot cover all or any. We have to have the card in order to test it's propper config. 
From what answers i could find quickly on the internet, you must switch back to USBInjectAll.kext and redo the USBMap yourself. I can help you to understand it or if you get stuck, but that is as much i can help. Let me know if you start. Cheers!

**Pull request closed without merging**
