### PR TITLE
ACPI update

### PR DESCRIPTION
**Pull request by Kinetik**
Deletion of those tables is not specific to this build. I don't know how i missed that.

### CODE REVIEW

**Comment by Xtendera** [comment]
You should remove the _.DS_Store_ files.

**Comment by Kinetik** [comment]
I actually do not know how to edit a pull request. I think he can just skip those files in the merge.

**Comment by Xtendera** [comment]
Just add a new commit to your fork with the files removed. I don't know how to edit commits either.

**Comment by varszegimarcell** [comment]
Due to the conflicts, (.DS_Store files) I cannot merge.

A few days ago I have added a .gitignore file to the repo, so any hidden sh@t like this cannot be committed and pushed to the repo in the future :D

**Comment by Kinetik** [comment]
Ok, then I will close it and commit it directly to main. I've re-forked it, something when wrong with the first fork.

**Pull request closed without merging**
