### PR TITLE
Updated to OpenCore 0.6.8

### PR DESCRIPTION
**Pull request by Xtendera**
I updated everything including the README. I left out ACPI as @varszegimarcell has already created a pull request for it. I also updated the config.plist based on [this](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/issues/21#issuecomment-822008598). I also deleted Bootstrap because it is not needed as of OpenCore 0.6.6.

### CODE REVIEW

**Comment by Kinetik** [comment]
Hi. Did you run also OCConfigCompare against the new sample.plist in the new 0.6.8 package?

**Comment by Xtendera** [comment]
Thank you for the tip, I did and there seem to be some missing keys. Let me see if I can find these in the docs.

**Comment by Xtendera** [comment]
I can't find most of these in the docs, I know one is missing and I removed it because it doesn't need it. WhateverGreen and AppleALC seem to handle it automatically based on the docs.

**Comment by varszegimarcell** [comment]
Also, we have to figure out the iGPU patching options in the config.plist.

**Comment by Xtendera** [comment]
@varszegimarcell The problem with the iGPU is that the config doesn't work with all Haswell CPUs. In fact, there was recently an issue: 
https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/issues/21
 Acording to the anwser, if your CPU was a native supported DevID, you can completely remove the keys inside DeviceProperties --> Add. But not all Haswell CPUs are, so removing it would allow some iGPUs to work, and others to stop working.

**Comment by varszegimarcell** [comment]
> 
> 
> @varszegimarcell The problem with the iGPU is that the config doesn't work with all Haswell CPUs. In fact, there was recently an issue:
> #21
> Acording to the anwser, if your CPU was a native supported DevID, you can completely remove the keys inside DeviceProperties --> Add. But not all Haswell CPUs are, so removing it would allow some iGPUs to work, and others to stop working.

I see, but these patches allow 4K and high refresh rates to work. We have to discuss what to do about that issue, so check it out, I left that case open at the moment.

**Comment by Xtendera** [comment]
Thanks, and then that, I got the config.plist up-to-date with the sample, so I will commit it, but we will have to see about the iGPU.

**Comment by Xtendera** [comment]
Hey @varszegimarcell, I think the next step for the guide is a troubleshooting page. I was just going through the issues and saw so many issues which needed a place in the guide. I am going to make a basic one at the bottom, you are welcome to edit it. I want to see what you think about it.

**Comment by Kinetik** [comment]
I would disagree if you don't mind :(. This EFI package should and is meant to be a "ready to use" product for this Optiplex series. Options for different installs(SFF, MT) are described in the readme, also for usage with dGPU, wifi etc. Any troubles must be addresed trough the issues board, discussed and corrected. After we will figure out the connectors patching for DP-HDMI cable users, this should also be included in the install readme as option. That is my opinion, sorry
You are so convinced that this is the solution to your case, that you want to push this to everyone. For me it is clear that you are misunderstanding the whole idea of the Framebuffer and connectors patching. Just because you are not needing a "pretentious" resolution, does not mean do others feel the same way. I think most will enjoy this Hackintosh better, if they have a clean image at a native resolution, rather than "acceptable" blurry image

**Comment by Xtendera** [comment]
I am so sorry. I just realized what I did. I removed the section and created a new branch in my fork to think about later. Sorry.

**Comment by Kinetik** [comment]
I am sorry too that i had to say it like that, but you are pushing commits to a open issue topic. After we investigate (and this can take time) and we do not find any working solution other then stripping down the patches, then your case should be posted as solution. Don't be upset because of me 🤗, we should be a team, and a team should focus in the same direction 😁 usually 🤣

**Comment by Xtendera** [comment]
Yes. :smiley: :thumbsup:

**Comment by Xtendera** [comment]
OK, where do we go from here? I am not very familiar with the graphics side of OC. I have invited both of you to edit my fork so that we can finalize it before we merge it with the master repo.

**Comment by Kinetik** [comment]
I have managed to get a working patch and pushed to my main. This will work with both DP-DP and DP-HDMI cables. The problem is with these cables is that DP-DP ones, cheap or expensive cables all deliver DP 1.4. While DP-HDMI cables are of two kinds on the market 1.2 and 1.4.  Most people get the 1.2 because it is in a price range of 10-15eur. The 1.4's are somewhere between 20-35eur. Now the big difference between these is huge in terms of display performance. 
The black screen you encountered is not just because the connector is not patching correctly, but also because the freq pushed at start-up was too much for the cable, therefore macOS could not even identify the monitor (no EEID). 

Now, using this patch will get you display output, but if your are using a 4k TV or Monitor with a 1.2 DP-HDMI monitor, the 3840x2160 resolution may appear in the list ( DO NOT USE IT) you will run into a black screen again. If this happens in any case, just delete the fbmem and stolenmem Framebuffer patches.  

I will come back to you will a few examples of cables and the difference in output they provide. Basically if you do not use the normal/preferred DP-DP cable and opting for a patch cable, you should always research your buy and get a 1.4 cable. With what, will be the same as DP-DP.

**Comment by Kinetik** [comment]
[patch.plist.zip](https://github.com/varszegimarcell/Optiplex-3020-Hackintosh-OpenCore/files/6361016/patch.plist.zip)
just the patch

**Comment by Kinetik** [comment]
For research if you want:

https://www.cablematters.com/blog/DisplayPort/displayport-1-4-vs-1-2
https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/https://osxlatitude.com/forums/topic/8723-enabling-dvidphdmi-and-increasing-vram-with-intel-haswell4th-gen-hd420044004600etc-igpu/

**Comment by varszegimarcell** [comment]
I will update the guide according to this issue.

I decided that we'll not fake any GPU IDs in the config, but we will leave all graphics patches in place. That will make graphics work properly on every HD4600 GPUs, regardless its specific Hardware ID. However, if anybody would use the HD4400, I will add a section in the guide discussing this topic, so you can add the fake HD4600 device ID by yourself.

I think that would be the best solution, what do you think about it?

**Comment by varszegimarcell** [comment]
Also, I will merge you PR, but I have to add the GPU patches back to the config (expect the ID) if you are OK with this solution.

**Comment by Xtendera** [comment]
Yes, I think this will do for now. If we get too many issues with this solution, then we will have to think about it.

**Comment by Kinetik** [comment]
In my opinion you should add an entry to the install readme, topmost, about the cable that must be used (no 1.2 DP-HDMI) and about the change (not remove) of device-id to the empty one for the HD4400 (if that is really the case). Too bad i cannot test.

If the 1.2 cable is used, user must remove only framebuffer-fbmem and framebuffer-stolenmem from the DeviceProperties. 

Device-id must be kept for one reason. If you remove it, still the same device-id applies. But, as it's well mentioned in Dortania's guide a lot of times, macOS is terrible at "guessing", so something that applies correctly sometimes, must be "written in stone" 😊. That is also how boot-arg's must be used. 
A boot-arg is a general patch, that should be used only to find witch one applies to you, and write that into the config, line by line. And so, you are adding to a more stable build.

It could be, that a monitor has an unsupported vendor, and even with a proper cable you will not get an output(i.e some ultra-wide's) that is where the patch comes in, as i raised the pipes and flags to support that.

In terms of how cable connectors should be patched, i understand more and more, i will be competent to upgrade this patch in the future as well, in regards to other iGPU's than the 4600, i can only rely on what i find online.

**Comment by Kinetik** [comment]
That being said, we must remove alcid=17 and go back to DeviceProperties. 
But i found out what the problem was initially. You use Number 17, when you should have used Data 11000000

**Comment by Kinetik** [comment]
@Xtendera I suspect that your problem is not the CPU or iGPU, just the cable. For that, to take it on myself I will go and buy a DP-HDMI 1.4 cable soon and test my theory. Please let's wait for that.

Makes no sense to me, sorry. In WhateverGreen's Framebuffer patching guide we have the same patch applying to all [Intel HD Graphics 4200-5200](https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.IntelHD.en.md#intel-hd-graphics-4200-5200-haswell-processors) for all Haswell processors
Xnip2021-04-23_21-51-26

Xnip2021-04-23_21-50-42

**Comment by Xtendera** [comment]
@Kinetik I think you have been mistaken. That wasn't my problem, it was someone else. I have no problem at all, actually. Right now I am making this post from my Optiplex 3020 MT running Big Sur 😄. But I do think this could be a solution to the problem. Try commenting that to the issue page for that specific issue.

**Comment by Kinetik** [comment]
You mentioned here a bout 4 days ago the relation to issue #21. That is the issue there. My mistake, sorry 
Then you must fill me in on what is not working for you. Your pull came immediately after that discussion and with that reference. I actually thought at one point that you are the same person. Really sorry!

**Comment by Xtendera** [comment]
No problem. We still need to figure out the graphic patching. The post that @varszegimarcell made was confusing. I didn't know if I was supposed to remove the platform-id from the config.plist. You did say to remove alcid, right?

**Comment by Kinetik** [comment]
Figure what exactly? What is not working for you? You never explained properly. Second time i ask!

**Comment by Xtendera** [comment]
Sorry for not explaining. Well according to @varszegimarcell, the GPU ID is having a problem. HD 4400 CPUs will not boot without changing the ID. He is thinking that we keep the ID that works for the HD 4600 CPUs, and add a section in the readme telling 4400 users to change it. Also, do we still need to change alcid to a HEX code?

**Comment by Kinetik** [comment]
No, actually the ID has no problem. As i tried to explain above, the patch should apply correctly and the same to all Haswell processors with graphics between HD4200 and HD5200. Improper cables can cause problems, but that should not be supported by us. This is a 100eur good working hackintosh, the least others can do is buy a decent cable 😊

So, you have the HD4400? With what processor?

Yes, we must write de layout-id in hex under dev propr and remove the boot arg. I will make a PR soon.

**Comment by Xtendera** [comment]
Wait, I think we still need to add the section about using only DP 1.4 and not 1.2. Should I do that or should I add it later.

**Comment by Kinetik** [comment]
I don't know, do what you want. I notice you are very excited to create pull requests and not revealing anything about system. I am trying to discuss the problem with you for nothing. Do me a favor please, stop mentioning me. You clearly have no connection to issues or development. Cheers

**Comment by Xtendera** [comment]
I am just trying to contribute to the repo. I do not have a problem with my system, I want to help others with theirs.

**Comment by Kinetik** [comment]
If you really want to help, start reading manuals for the specifics of this hardware, learn about best practises in settings and come up with updates of your own in contribution to this repo. We can create pull requests and update the EFI by ourselves thank you. If you just want to practice creating pull requests, please leave me out of it and stop mentioning me or confirm my work. This conversation ends here. Cheers

**Comment by Xtendera** [comment]
:

**Pull request closed without merging**
