### PR TITLE
Graphics patch update to support HDMI cables & Audio properties reassigmnent

### PR DESCRIPTION
**Pull request by Kinetik**

### CODE REVIEW

**Comment by Kinetik** [comment]
Also includes the USBMap update PR

**Comment by Xtendera** [comment]
Looks good. @Kinetik I think we can merge both the OC 0.6.8 and this one.

**Comment by Kinetik** [comment]
Notes: After long trials and errors i found that  the patch is doing it's job no matter what pipes and flags i set.  it all comes down to using a DP to HDMI cable type 1.4. Nobody should use a 1.2, as it's insufficient for iGPU to render correct output. I have added the driver support to get rig of some glitching when using HDMI cables and removed the device-id as i understood you preffered like this. Makes no difference.

I removed the alcid boot arg and added the correct deviceproperty assignment.

**Comment by Kinetik** [comment]
https://linustechtips.com/topic/957929-how-to-tell-the-difference-between-display-port-12-and-14-cables/?do=findComment&comment=11625938

**Comment by Kinetik** [comment]
@varszegimarcell you will get 2 more PR from me. 
One for Open Canopy and another for translating the graphics boot args to DeviceProperties. Use them if you like.
With those will conclude my contribution to your EFI. Cheers

**Comment by Kinetik** [comment]
and one other thing @varszegimarcell, be careful of what solutions you adopt in the future. Many with other users with systems similar to the 3020 will use this EFI, but will not work well for them, and you will get issues and possibly also PR's for things that have nothing to do with this actual build. 
I have decided to buy a M1 Mac mini in the end :)), I will receive by the end of next month. So, this was it for me. This unit will go to my niece :).
I hope I helped. It was a good school for me with the various patches and ACPI mappings. It is a way more stable build now, specially with the USBMap. 
Good luck moving forward with it! Cheers!

**Comment by varszegimarcell** [comment]
> and one other thing @varszegimarcell, be careful of what solutions you adopt in the future. Many other users with systems similar to the 3020 will use this EFI, but will not work well for them, and you will get issues and possibly also PR's for things that have nothing to do with this actual build.
> I have decided to buy a M1 Mac mini in the end :)), I will receive by the end of next month. So, this was it for me. This unit will go to my niece :).
> I hope I helped. It was a good school for me with the various patches and ACPI mappings. It is a way more stable build now, specially with the USBMap.
> Good luck moving forward with it! Cheers!

Hey! 

Thanks for your contribution @Kinetik and wish you good luck in the future!

About the PR part, I can only say that sadly I cannot focus enough on this project at the moment enough, as I started my masters, and also I have a job. But I will check out all PR’s and will not adopt them if these are not up to my standards, nor I hadn’t tested the PR. Sadly, I can’t be active here on a daily basis, but I will check things out weekly at least.

I cannot comment on the drama part, as seems like all the comments and issues were removed related to that.

**Comment by varszegimarcell** [comment]
Also, I have to update to OC 0.6.8 if I am correct, but I have to test these patches first.

**Comment by Kinetik** [comment]
It was my pleasure. Better forget about that drama. What you should remember from that is that "faking" the device-id is just a word, just like "assign or set". If you remove it for this sff build, still it will apply, but for a more stable system, it should be in the config. This is what I understood from dortania, and I READ IT ALL :))). Also, the preferred OC plist build is by writing properties lines in hex, not by using boot-args. Those are meant to be a temporary solution (only some systems are recommended to run only on those). 

Don't be so quick to update to each version, read the release notes. If it does not contain any major improvement, you can easily skip an update or two.

**Comment by Kinetik** [comment]
0.6.9 is just out now, you can just update to that. Or, maybe i can do it. I will still have this unit for a few weeks. If i have time, i will do it tomorrow

**Comment by varszegimarcell** [comment]
> It was my pleasure. Better forget about that drama. What you should remember from that is that "faking" the device-id is just a word, just like "assign or set". If you remove it for this sff build, still it will apply, but for a more stable system, it should be in the config. This is what I understood from dortania, and I READ IT ALL :))). Also, the preferred OC plist build is by writing properties lines in hex, not by using boot-args. Those are meant to be a temporary solution (only some systems are recommended to run only on those).
> 
> Don't be so quick to update to each version, read the release notes. If it does not contain any major improvement, you can easily skip an update or two.

You're probably right about that. 

I decided that I add a troubleshooting section to the guide, so if anyone has this black screen issue, he can fix it. Leaving in the ID means that it is ready to use with a HD4400 either, you I think it is more universal. 

I'm working on the OC 0.6.9 update, as far as I can see, no huge changes happened.

**Pull request merged**
